---
- name: Add Puppet Labs GPG key.
  ansible.builtin.rpm_key:
    key: https://yum.puppet.com/RPM-GPG-KEY-puppet-20250406
    state: present

- name: Add Puppet Labs repositories.
  ansible.builtin.dnf:
    name: "{{ puppet_yum_rpm }}"
    state: present
