---
- name: Converge
  hosts: all
  become: true
  gather_facts: yes

  # pre_tasks:
  #   - include: java-11.yml

  roles:
    - role: buluma.java
      when: ansible_os_family == 'Debian'
    - role: buluma.puppet
